const getActionTypes = () => ({
  CHECK_AUTHORIZATION: "CHECK_AUTHORIZATION",
  CHECK_AUTHORIZATION_SUCCESS: "CHECK_AUTHORIZATION_SUCCESS",
  CHECK_AUTHORIZATION_UNAUTH: "CHECK_AUTHORIZATION_UNAUTH",
  CHECK_AUTHORIZATION_FAIL: "CHECK_AUTHORIZATION_FAIL",

  USER_LOGIN: "USER_LOGIN",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",

  SOCIAL_LOGIN: "SOCIAL_LOGIN",
  SOCIAL_LOGIN_SUCCESS: "SOCIAL_LOGIN_SUCCESS",
  SOCIAL_LOGIN_FAIL: "SOCIAL_LOGIN_FAIL",

  USER_SIGNUP: "USER_SIGNUP",
  USER_SIGNUP_SUCCESS: "USER_SIGNUP_SUCCESS",
  USER_SIGNUP_FAIL: "USER_SIGNUP_FAIL",

  USER_LOGOUT: "USER_LOGOUT",
  RESET_ERROR_MESSAGE: "RESET_ERROR_MESSAGE",

  GET_HOME: "GET_HOME",
  GET_HOME_SUCCESS: "GET_HOME_SUCCESS",
  GET_HOME_FAIL: "GET_HOME_FAIL",

  GET_METADATA: "GET_METADATA",
  GET_METADATA_SUCCESS: "GET_METADATA_SUCCESS",
  GET_METADATA_FAIL: "GET_METADATA_FAIL",

  GET_COINDATA: "GET_COINDATA",
  GET_COINDATA_SUCCESS: "GET_COINDATA_SUCCESS",
  GET_COINDATA_FAIL: "GET_COINDATA_FAIL",

  GET_CRYPTOFOLIOS: "GET_CRYPTOFOLIO",
  GET_CRYPTOFOLIOS_SUCCESS: "GET_CRYPTOFOLIO_SUCCESS",
  GET_CRYPTOFOLIOS_FAIL: "GET_CRYPTOFOLIO_FAIL",
});

export default getActionTypes;
